# Generated by Django 3.2.15 on 2022-09-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='pics')),
                ('name1', models.CharField(max_length=250)),
                ('desc1', models.TextField()),
            ],
        ),
    ]
